version: '3.9'

services:
  web:
      build: .
      ports:
          - 8081:8000
      volumes:
          - .:/it_solution
      depends_on:
          - db
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=runtext_db

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - 8080:80
    depends_on:
      - db

volumes:
  data: null